# Generated by Django 3.2.4 on 2021-06-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16, unique=True)),
                ('c_password', models.CharField(max_length=256)),
                ('c_email', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'edu_customer',
            },
        ),
    ]
